######################################################################
# Automatically generated by qmake (1.04a) Mon Dec 22 03:40:07 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += string.cpp
